service: qr-code-generator

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1
  memorySize: 256
  timeout: 10

functions:
  app:
    handler: index.handler
    events:
    - http:
        path: /
        method: ANY
        cors: true
    - http:
        path: /{proxy+}
        method: ANY
        cors: true

plugins:
- serverless-offline
- serverless-mocha-plugin


custom:
  serverless-offline:
    httpPort: 3000
